export * from './tech-icons'

export const ICON_API = 'icons/api.svg'
export const ICON_CICD = 'icons/cicd.svg'
export const ICON_DATABASE = 'icons/database.svg'
export const ICON_EMAIL = 'icons/email.svg'
export const ICON_ENVELOPE = 'icons/envelope.svg'
export const ICON_FRONTEND = 'icons/frontend.svg'
export const ICON_LINKEDIN = 'icons/linkedin.svg'
export const ICON_NEW_TAB = 'icons/new-tab.svg'
